Repository fossasia/susi.ai, pull requests merged in 2019-08, with the labels that each got.

#2723 Fix chatApp bugs #2711
  src/components/ChatApp/MessageListItem/MessageListItem.react.js
  src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
  src/components/ChatApp/MessageSection/MessageSection.react.js
Labels: bug

#2778 Fix scoll to bottom on opening of chat#2718
  src/components/ChatApp/MessageComposer.react.js
  src/components/ChatApp/MessageSection/MessageSection.react.js
Labels: Priority: Urgent, bug

#2781 Fix create skill menu on left in browseSkill #2530
  src/components/cms/BrowseSkill/BrowseSkill.js
Labels: bug

#2777 Add email messages #2547
  src/components/Admin/Admin.js
  src/components/Admin/Messages/index.js
  src/components/Admin/Messages/message-config.js
  src/components/Admin/Messages/table-config.js
Labels: enhancement

#2766 Add device setup page for SUSI smart speaker #2742
  .env
  src/App.js
  src/apis/index.js
  src/components/smart-speaker/Setup.js
  src/components/smart-speaker/susilogo.png
Labels: WIP

#2802 Fix API Keys response types #2801
  src/components/Admin/Settings/ConfigKeys/index.js
  src/index.js
Labels: Priority: Urgent

#2803 Add reset password component #2800
  src/App.js
  src/__tests__/components/Auth/ResetPassword/ResetPassword.js
  src/apis/index.js
  src/components/Auth/ResetPassword/index.js
  src/components/shared/Dialog/index.js
Labels: account, enhancement

#2819 Fixes #2818: Add feature for planned skills
  src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
  src/redux/reducers/messages.js
  src/utils/formatMessage.js
  src/utils/generateMessage.js
  src/utils/scheduler.js
Labels: feature

#2810 Add functionality to enable/disable captcha #2796
  src/components/About/Blog/index.js
  src/components/Auth/ChangePassword/ChangePassword.react.js
  src/components/Auth/Login/Login.react.js
  src/components/Auth/SignUp/SignUp.react.js
  src/components/Settings/Settings.react.js
  src/redux/reducers/app.js
Labels: feature

#2795 Admin: Enhance message table, remove all table scroll
  src/components/Admin/ListSkills/constants.js
  src/components/Admin/ListUser/constants.js
  src/components/Admin/Messages/index.js
  src/components/Admin/Messages/message-config.js
  src/components/Admin/Messages/table-config.js
  src/components/Admin/Settings/Slideshow/constants.js
  src/components/shared/Dialog/index.js
  src/components/shared/table.js
Labels: enhancement

#2837 Fix api keys failing bug #2836
  src/redux/reducers/app.js
Labels: bug

#2821 Improve documentation of SUSI.AI #2811
  README.md
  docs/API_KEYS.md
  docs/ARCHITECTURE.md
  docs/DEPLOY.md
  docs/DESIGN.md
  docs/PROJECT_INFORMATION.md
  docs/RECOMMENDED_READING.md
  docs/TRANSLATION.md
  docs/images/color/000000.png
  docs/images/color/071E3D.png
  docs/images/color/4285F4.png
  docs/images/color/C6DAFB.png
  docs/images/color/E0E0E0.png
  docs/images/color/F3F2F4.png
  docs/images/color/FCFCFC.png
  docs/images/color/FF9631.png
  docs/images/color/FFFFFF.png
  src/App.js
  src/__tests__/components/About/Contact/Contact.js
  src/__tests__/components/About/Privacy/Privacy.js
  src/__tests__/components/About/Terms/Terms.js
  src/components/About/Contact/Contact.react.js
  src/components/About/Privacy/Privacy.react.js
  src/components/About/Terms/Terms.react.js
Labels: documentation

#2842 Fix message list in admin #2838
  src/components/Admin/Messages/index.js
  src/components/Admin/Messages/message-config.js
  src/components/Admin/Messages/table-config.js
Labels: bug

#2861 Fix devices tab table scroll
  src/components/Admin/ListDevices/constants.js
  src/components/Admin/ListDevices/index.js
  src/components/shared/table.js
Labels: bug

#2843 Admin Dashboard: Erroneous dates in analytics #2829
  src/components/Admin/AdminTab/AdminTab.js
  src/utils/findUnixEpochDateIndex.js
Labels: bug

#2864 Fix devices tab table scroll #2860
  src/components/Admin/ListDevices/constants.js
  src/components/Admin/ListDevices/index.js
Labels: bug

#2847 Add login in the setup page[Smart Speaker] #2824
  src/App.js
  src/apis/index.js
  src/components/smart-speaker/Setup.js
  src/components/smart-speaker/susilogo.svg
Labels: feature

#2871 Fix entry point #2869
  src/App.js
Labels: Priority: High, bug

#2833 Admin: Provide more options to edit users
  src/apis/index.js
  src/components/Admin/ListUser/constants.js
  src/components/Admin/ListUser/index.js
  src/components/Settings/AccountTab.react.js
  src/components/Settings/ChatAppTab.react.js
  src/components/Settings/MicrophoneTab.react.js
  src/components/Settings/MobileTab.react.js
  src/components/Settings/Settings.react.js
  src/components/Settings/SpeechTab.react.js
  src/components/Settings/ThemeChangeTab.react.js
  src/redux/reducers/settings.js
  src/utils/getAvatarProps.js
Labels: feature

#2867 Admin Message Tab: Add Captcha column with checkbox #2796
  src/App.js
  src/__tests__/components/Admin/Messages/RecaptchaOptions.js
  src/__tests__/components/Admin/Messages/index.js
  src/__tests__/components/Admin/Settings/ReCaptcha/index.js
  src/apis/index.js
  src/components/Admin/Messages/RecaptchaOptions.js
  src/components/Admin/Messages/message-config.js
  src/components/Admin/Settings/ReCaptcha/index.js
  src/components/Admin/Settings/index.js
  src/components/Auth/ChangePassword/ChangePassword.react.js
  src/components/Auth/Login/Login.react.js
  src/components/Auth/SignUp/SignUp.react.js
  src/redux/actionTypes/index.js
  src/redux/actions/app.js
  src/redux/reducers/app.js
Labels: feature

#2794 Admin: Improve Bots page, add columns
  src/components/Admin/ListBots/constants.js
  src/components/Admin/ListBots/index.js
Labels: enhancement

#2884 Fix bug in loading of skills
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/redux/reducers/skill.js
  src/redux/reducers/skills.js
Labels: bug

#2890 Add Unlink device #2887
  src/apis/index.js
  src/components/smart-speaker/Control.js
Labels: dependent on server, feature
