Repository fossasia/susi.ai, pull requests merged in 2019-06, with the labels that each got.

#2157 Integrate User Avatar in Settings #1837, Create getUserAvatarLink utility #2154
  public/defaultAvatar.png
  src/__tests__/components/ChatApp/Settings/Avatar.js
  src/apis/index.js
  src/components/ChatApp/Settings/AccountTab.react.js
  src/components/ChatApp/Settings/Avatar.js
  src/components/ChatApp/Settings/Settings.css
  src/components/ChatApp/TopBar.react.js
  src/components/StaticAppBar/StaticAppBar.react.js
  src/redux/actionTypes/index.js
  src/redux/actions/app.js
  src/redux/reducers/app.js
  src/utils/getAvatarProps.js
Labels: feature

#2218 Fix styling in Dialog boxes for auth #2217, add styled components, mobile view
  src/components/Auth/AuthStyles.js
  src/components/Auth/ForgotPassword/ForgotPassword.react.js
  src/components/Auth/Login/Login.css
  src/components/Auth/Login/Login.react.js
  src/components/Auth/SignUp/SignUp.css
  src/components/Auth/SignUp/SignUp.react.js
  src/components/ChatApp/ChatApp.css
  src/components/shared/Container.js
Labels: UI/UX, refactor

#2228 Fixes #2227: Upgrade outdated packages & enable hot-reload
  .eslintrc
  README.md
  package.json
  src/App.js
  src/components/Admin/ListSkills/ListSkills.js
  src/components/Admin/ListUser/ListUser.js
  src/components/Auth/Login/Login.react.js
  src/components/Auth/SignUp/SignUp.react.js
  src/components/Blog/Blog.react.js
  src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
  src/components/ChatApp/MessageListItem/helperFunctions.react.js
  src/components/ChatApp/TopBar.react.js
  src/components/Contact/Contact.react.js
  src/components/CookiePolicy/CookiePolicy.react.js
  src/components/Devices/Devices.react.js
  src/components/Dialog/Share.js
  src/components/Overview/Overview.react.js
  src/components/Privacy/Privacy.react.js
  src/components/Settings/AccountTab.react.js
  src/components/Settings/Avatar.js
  src/components/Settings/DevicesTab.react.js
  src/components/Settings/PreviewThemeChat.js
  src/components/Settings/ThemeChanger.js
  src/components/Support/Support.react.js
  src/components/TableComplex/RemoveDeviceDialog.react.js
  src/components/TableComplex/TableComplex.react.js
  src/components/Terms/Terms.react.js
  src/components/cms/AuthorSkills/AuthorSkills.js
  src/components/cms/BotBuilder/BotBuilderPages/DesignViews/UIView.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/Dashboard/MyAnalytics.js
  src/components/cms/Dashboard/MyRatings.js
  src/components/cms/Dashboard/MySkills.js
  src/components/cms/SkillCardGrid/SkillCardGrid.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/components/cms/SkillCardScrollList/SkillCard.js
  src/components/cms/SkillCreator/SkillCreator.js
  src/components/cms/SkillCreator/SkillViews/CodeView.js
  src/components/cms/SkillCreator/SkillViews/TreeView.js
  src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
  src/components/cms/SkillHistory/SkillHistory.js
  src/components/cms/SkillPage/SkillListing.js
  src/components/cms/SkillRating/SkillRatingCard.js
  src/components/cms/SkillRollBack/SkillRollBack.js
  src/components/cms/SkillVersion/SkillVersion.js
  src/components/shared/PieChartContainer.js
  src/images/defaultAvatar.png
  src/index.js
  src/redux/configureStore.js
  src/redux/create.js
  src/redux/reducers/index.js
  src/store.js
  src/utils/index.js
Labels: Priority: High, enhancement, feature

#2241 Fixes #2239: Increase memory for surge build
  package.json
Labels: Priority: Urgent

#2230 Remove the need to click on cross to Upload Photo
  src/components/Settings/AccountTab.react.js
  src/components/Settings/Avatar.js
Labels: enhancement

#2237 Open account settings on avatar click, Add Styled components in TopBar
  package.json
  src/components/ChatApp/TopBar.css
  src/components/ChatApp/TopBar.react.js
  src/components/StaticAppBar/StaticAppBar.react.js
  src/components/shared/TopBarStyles.js
Labels: UI/UX, enhancement

#2232 Skill Usage PieChart in Dashboard#2231, CSS Cleanup#2219, Dialog Transition #2233
  docs/Skill_Tutorial.md
  src/App.js
  src/components/ChatApp/TopBar.react.js
  src/components/Contact/Contact.css
  src/components/Overview/Overview.css
  src/components/StaticAppBar/StaticAppBar.react.js
  src/components/Support/Support.css
  src/components/Team/Team.css
  src/components/Terms/Terms.css
  src/components/cms/Dashboard/Dashboard.css
  src/components/cms/Dashboard/Dashboard.js
  src/components/cms/Dashboard/MyAnalytics.js
  src/components/cms/Dashboard/MyRatings.js
  src/components/cms/Dashboard/MySkills.js
  src/components/cms/SkillCreator/SkillCreator.js
  src/components/cms/SkillUsageCard/SkillUsageCard.js
  src/components/shared/Link.js
  src/components/shared/PieChartContainer.js
  src/utils/urls.js
Labels: UI/UX, bug, refactor

#2244 Fixes #2224: Fix the test example feature
  src/App.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/components/cms/SkillPage/SkillListing.js
  src/history.js
  src/redux/reducers/messages.js
Labels: bug

#2226 Use 2 dialog confirmation approach for DeleteAccount #2225
  src/App.js
  src/__tests__/components/Auth/DeleteAccount/ConfirmDeleteAccount.js
  src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
  src/components/Auth/DeleteAccount/DeleteAccount.react.js
  src/components/Dialog/DialogSection.react.js
  src/components/Settings/AccountTab.react.js
Labels: enhancement

#2260 Fix Cookies policy, Remove IconButton on User not logged in App Bar
  src/App.js
  src/components/ChatApp/TopBar.react.js
  src/components/CookiePolicy/CookiePolicy.react.js
  src/components/StaticAppBar/StaticAppBar.react.js
  src/redux/reducers/app.js
Labels: bug

#2246 Fix BrowseSkill, integrated styled components, mobile view, Codacy Doc
  README.md
  package.json
  src/components/ChatApp/ChatApp.css
  src/components/Footer/Footer.react.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/BrowseSkill/SkillStyle.js
  src/components/cms/BrowseSkill/custom.css
  src/components/cms/SkillCardGrid/SkillCardGrid.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/components/cms/SkillCardList/SkillCardStyle.js
  src/components/cms/SkillCardScrollList/ScrollStyle.js
  src/components/cms/SkillCardScrollList/SkillCard.js
  src/components/cms/SkillCardScrollList/SkillCardScrollList.js
  src/components/cms/SkillCardScrollList/SkillCardScrollList.min.css
  src/components/cms/SkillCardStyle.js
  src/components/cms/SkillRating/SkillRating.js
  src/components/cms/SkillsStyle.js
  src/redux/reducers/skills.js
Labels: Clean Up, UI/UX, bug, enhancement, refactor

#2263 [FIX] : Fix customThemeValue property undefined error with setting de…
  src/redux/reducers/settings.js
Labels: bug

#2271 Add Styled components in SkillUsageCard, SkillRating, SkillHistory, SkillFeedbackCard
  src/components/cms/CountryWiseSkillUsageCard/CountryWiseSkillUsageCard.css
  src/components/cms/CountryWiseSkillUsageCard/CountryWiseSkillUsageCard.js
  src/components/cms/Dashboard/MyAnalytics.js
  src/components/cms/SkillFeedbackCard/SkillFeedbackCard.css
  src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
  src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
  src/components/cms/SkillHistory/SkillHistory.css
  src/components/cms/SkillHistory/SkillHistory.js
  src/components/cms/SkillPage/SkillListing.css
  src/components/cms/SkillPage/SkillListing.js
  src/components/cms/SkillRating/SkillRatingCard.css
  src/components/cms/SkillRating/SkillRatingCard.js
  src/components/cms/SkillRollBack/SkillRollBack.js
  src/components/cms/SkillUsageCard/SkillUsageCard.css
  src/components/cms/SkillUsageCard/SkillUsageCard.js
  src/components/shared/Container.js
  src/components/shared/PieChartContainer.js
  src/components/shared/Typography.js
Labels: UI/UX, refactor

#2310 Fix Travis Fail Error #2309
  package.json
Labels: Priority: Urgent, bug

#2301 Add Loader in missing places, fix change password, add styled-component
  src/components/Auth/ChangePassword/ChangePassword.css
  src/components/Auth/ChangePassword/ChangePassword.react.js
  src/components/Auth/SignUp/SignUp.react.js
  src/components/Settings/AccountTab.react.js
  src/components/Settings/ChatAppTab.react.js
  src/components/Settings/MicrophoneTab.react.js
  src/components/Settings/MobileTab.react.js
  src/components/Settings/SpeechTab.react.js
  src/components/Settings/ThemeChangeTab.react.js
  src/components/shared/PasswordStrengthBar.js
Labels: bug, enhancement, refactor

#2298 Fix Author Skills, Add Styled components #2296
  src/components/Dialog/DialogSection.react.js
  src/components/cms/AuthorSkills/AuthorSkills.css
  src/components/cms/AuthorSkills/AuthorSkills.js
  src/components/cms/SkillPage/SkillListing.js
Labels: bug, refactor

#2331 Fix Speech Output Language Settings, redirect on create skill
  src/components/Settings/TextToSpeechSettings.react.js
  src/components/cms/SkillCreator/SkillCreator.js
  src/components/cms/SkillRollBack/SkillRollBack.js
Labels: bug

#2287 CSS Fixes in skill description
  src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
  src/components/cms/SkillPage/SkillListing.css
  src/components/cms/SkillPage/SkillListing.js
  src/components/cms/SkillRating/SkillRatingCard.js
  src/components/cms/SkillUsageCard/SkillUsageCard.js
Labels: wontfix

#2294 Fix Delete Modal Dialog, Standardise dialog, Admin delete button
  src/__tests__/Admin/ListSkills/ConfirmSkillDialog.js
  src/__tests__/Admin/ListSkills/DeleteSkillDialog.js
  src/__tests__/Admin/ListSkills/EditSkillDialog.js
  src/__tests__/Admin/ListSkills/RestoreSkillDialog.js
  src/__tests__/Admin/SystemSettings/DeleteSystemSettingsDialog.js
  src/__tests__/Admin/SystemSettings/UpdateSystemSettingsDialog.js
  src/__tests__/components/BotBuilder/DeleteBotDialog.js
  src/__tests__/components/SkillCreator/DeleteSkillDialog.js
  src/__tests__/components/SkillFeedbackPage/DeleteFeedbackDialog.js
  src/__tests__/components/SkillFeedbackPage/EditFeedbackDialog.js
  src/__tests__/components/SkillPage/ReportSkillDialog.js
  src/components/Admin/ListSkills/ConfirmSkillDialog.js
  src/components/Admin/ListSkills/DeleteSkillDialog.js
  src/components/Admin/ListSkills/EditSkillDialog.js
  src/components/Admin/ListSkills/ListSkills.js
  src/components/Admin/ListSkills/RestoreSkillDialog.js
  src/components/Admin/SystemSettings/DeleteSystemSettingsDialog.js
  src/components/Admin/SystemSettings/SystemSettings.js
  src/components/Admin/SystemSettings/UpdateSystemSettingsDialog.js
  src/components/Auth/AuthStyles.js
  src/components/Auth/DeleteAccount/ConfirmDeleteAccount.react.js
  src/components/Dialog/DialogSection.react.js
  src/components/Settings/DevicesTab/RemoveDeviceDialog.js
  src/components/cms/BotBuilder/BotBuilder.js
  src/components/cms/BotBuilder/DeleteBotDialog.js
  src/components/cms/SkillCreator/DeleteSkillDialog.js
  src/components/cms/SkillCreator/SkillCreator.js
  src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
  src/components/cms/SkillFeedbackPage/DeleteFeedbackDialog.js
  src/components/cms/SkillFeedbackPage/EditFeedbackDialog.js
  src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
  src/components/cms/SkillPage/ReportSkillDialog.js
  src/components/cms/SkillPage/SkillListing.js
  src/components/shared/Container.js
Labels: bug, enhancement, refactor

#2264 Fix about pages
  src/components/Blog/Blog.css
  src/components/Blog/Blog.react.js
  src/components/Button/ToTopButton.react.js
  src/components/Devices/Devices.css
  src/components/Devices/Devices.react.js
  src/components/Overview/Overview.css
  src/components/Overview/Overview.react.js
  src/components/StaticAppBar/StaticAppBar.react.js
  src/components/Support/Support.css
  src/components/Support/Support.react.js
  src/components/Team/Team.css
  src/components/Team/Team.react.js
  src/components/shared/About.js
Labels: UI/UX, bug, enhancement, refactor

#2313 Fix CSS of message footer #2312, test example for skill #2311
  src/__tests__/components/ChatApp/ChatApp.js
  src/components/ChatApp/ChatApp.react.js
  src/components/ChatApp/MessageComposer.react.js
  src/components/ChatApp/MessageListItem/Feedback.react.js
  src/components/ChatApp/MessageListItem/helperFunctions.react.js
Labels: UI/UX, bug

#2333 Fix console errors, skill search functionality loading, team links
  src/components/Admin/AdminTab/AdminTab.js
  src/components/Auth/ChangePassword/ChangePassword.react.js
  src/components/ProtectedRoute/index.js
  src/components/Settings/MobileTab.react.js
  src/components/Settings/SettingsTabWrapper.js
  src/components/StaticAppBar/StaticAppBar.react.js
  src/components/Team/SocialLinkButtons.js
  src/components/cms/BotBuilder/BotBuilder.js
  src/components/cms/BotBuilder/BotBuilderPages/Configure.js
  src/components/cms/BotBuilder/BotBuilderPages/Design.js
  src/components/cms/BotBuilder/BotWizard.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/SkillCreator/SkillCreator.js
  src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
  src/components/cms/SkillPage/SkillListing.js
  src/redux/reducers/app.js
  src/redux/reducers/create.js
  src/redux/reducers/settings.js
  src/redux/reducers/skills.js
Labels: bug, enhancement, refactor

#2389 Fix logo on Page not Found #2348
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.react.js
Labels: UI/UX, bug

#2392 Common bug fixes, Fix Popover Bugs
  src/components/Dialog/DialogSection.react.js
  src/components/StaticAppBar/Popper.js
  src/components/StaticAppBar/StaticAppBar.react.js
  src/components/StaticAppBar/TopMenu.js
  src/components/cms/SkillVersion/SkillVersion.css
  src/components/cms/SkillVersion/SkillVersion.js
Labels: Priority: Urgent
