Repository fossasia/susi.ai, pull requests merged in 2019-07, with the labels that each got.

#2406 Remove TopBar, reuse StaticAppBar #2373
  src/App.js
  src/__tests__/components/ChatApp/TopBar.js
  src/components/ChatApp/ChatApp.css
  src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
  src/components/ChatApp/MessageSection/MessageSection.react.js
  src/components/ChatApp/TopBar.react.js
  src/components/NavigationBar/Styles.js
  src/components/NavigationBar/TopMenu.js
  src/components/NavigationBar/index.js
  src/components/shared/TopBarStyles.js
Labels: Clean Up, refactor

#2404 Fix map in Chat app
  src/components/ChatApp/ChatApp.css
  src/components/ChatApp/MessageListItem/MessageBubbleStyle.js
Labels: bug

#2385 Fixed mobile view for auth dialog
  src/components/Auth/AuthStyles.js
  src/components/Auth/ForgotPassword/ForgotPassword.react.js
  src/components/Auth/Login/Login.react.js
  src/components/Auth/SignUp/SignUp.react.js
Labels: UI/UX

#2428 Simplify and enhance menus #2423
  src/components/Footer/Footer.react.js
  src/components/NavigationBar/TopMenu.js
  src/components/NavigationBar/constants.js
  src/components/NavigationBar/index.js
Labels: Priority: High, enhancement

#2438 Fixes #2437: Use .env for API_URL
  .env
  .gitignore
  src/utils/urls.js
Labels: feature

#2445 Fix Chat underline link #2444
  src/components/NavigationBar/TopMenu.js
Labels: bug

#2443 Fix preview chat response based on live skill #2432
  src/components/cms/BotBuilder/Preview/Preview.js
Labels: bug

#2415 Integrate styled-component in Custom Theme Changer, Add Mobile View
  src/__tests__/components/shared/ColorPicker.js
  src/__tests__/components/shared/ColorPicker/ColorPicker.js
  src/components/ChatApp/ChatApp.css
  src/components/Dialog/DialogSection.react.js
  src/components/Settings/PreviewThemeChat.css
  src/components/Settings/PreviewThemeChat.js
  src/components/Settings/ThemeChanger.js
  src/components/cms/BotBuilder/BotBuilderPages/DesignViews/UIView.js
  src/components/shared/ColorPickerComponent/ColorPicker.css
  src/components/shared/ColorPickerComponent/index.js
Labels: UI/UX, refactor

#2429 Implement Slider on Skills page #2427
  src/__tests__/components/SkillsSlideshow/SkillsSlideshow.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/SkillSlideshow/constants.js
  src/components/cms/SkillSlideshow/index.css
  src/components/cms/SkillSlideshow/index.js
  src/images/raspberry-pi.png
  src/images/susi-android.png
  src/images/susi-local-machine.png
Labels: Priority: High

#2409 Integrate styled components and fix mobile view in Bot Builder and skill wizard
  src/App.js
  src/components/cms/BotBuilder/BotBuilder.css
  src/components/cms/BotBuilder/BotBuilder.js
  src/components/cms/BotBuilder/BotBuilderPages/Configure.js
  src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/CodeView.js
  src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/UIView.js
  src/components/cms/BotBuilder/BotBuilderPages/Deploy.js
  src/components/cms/BotBuilder/BotBuilderPages/Design.js
  src/components/cms/BotBuilder/BotBuilderPages/DesignViews/CodeView.js
  src/components/cms/BotBuilder/BotBuilderPages/DesignViews/UIView.js
  src/components/cms/BotBuilder/BotBuilderWrap.js
  src/components/cms/BotBuilder/BotWizard.js
  src/components/cms/SkillCreator/SkillViews/CodeView.js
  src/components/cms/SkillCreator/SkillWizard.css
  src/components/cms/SkillCreator/SkillWizard.js
  src/components/shared/CircularLoader.js
Labels: Priority: High

#2457 Error mesasge
  package.json
  src/components/Auth/AuthStyles.js
  src/components/Auth/Login/Login.react.js
Labels: UI/UX

#2460 Integrate Styled component in CircleImage #2420
  src/components/shared/CircleImage/CircleImage.css
  src/components/shared/CircleImage/index.js
Labels: refactor

#2471 Hide slider on search, fix position #2469
  package.json
  src/components/cms/BrowseSkill/BrowseSkill.js
Labels: bug

#2463 Play latest SoundCloud song from multiple songs #2462
  src/components/ChatApp/MessageListItem/generateMessageBubbleUtil.js
Labels: bug

#2479 Add line break in Admin skills on enough space #2476
  src/components/Admin/ListSkills/ListSkills.js
Labels: bug, wontfix

#2490 Remove slug /skills across web-app
  src/App.js
  src/__tests__/components/SkillCreator/SkillWizard.js
  src/__tests__/components/SkillHistory/SkillHistory.js
  src/__tests__/components/SkillRollBack/SkillRollBack.js
  src/__tests__/components/SkillVersion/SkillVersion.js
  src/components/NavigationBar/TopMenu.js
  src/components/NavigationBar/constants.js
  src/components/cms/AuthorSkills/AuthorSkills.js
  src/components/cms/BotBuilder/BotBuilder.js
  src/components/cms/BotBuilder/BotWizard.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/BrowseSkill/BrowseSkillByCategory.js
  src/components/cms/BrowseSkill/BrowseSkillByLanguage.js
  src/components/cms/Dashboard/MyRatings.js
  src/components/cms/Dashboard/MySkills.js
  src/components/cms/Dashboard/index.js
  src/components/cms/SkillCardGrid/SkillCardGrid.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/components/cms/SkillCardScrollList/SkillCard.js
  src/components/cms/SkillCreator/SkillCreator.js
  src/components/cms/SkillCreator/SkillWizard.js
  src/components/cms/SkillFeedbackPage/SkillFeedbackPage.js
  src/components/cms/SkillHistory/SkillHistory.js
  src/components/cms/SkillPage/SkillListing.js
  src/components/cms/SkillRollBack/SkillRollBack.js
  src/components/cms/SkillVersion/SkillVersion.js
Labels: bug

#2464 Fix BotBuilder Bugs #2422
  src/apis/index.js
  src/components/cms/BotBuilder/BotBuilderPages/DesignViews/UIView.js
  src/components/cms/BotBuilder/BotWizard.js
  src/components/cms/BotBuilder/Preview/Preview.js
  src/components/cms/SkillCreator/SkillWizard.js
  src/redux/actions/create.js
  src/redux/reducers/create.js
Labels: bug, enhancement

#2502 Implement Subtab for Slider Details on Admin #2455
  src/__tests__/Admin/SystemSettings/ConfigKeys/DeleteSystemSettingsDialog.js
  src/__tests__/Admin/SystemSettings/ConfigKeys/UpdateSystemSettingsDialog.js
  src/__tests__/Admin/SystemSettings/ConfigKeys/index.js
  src/__tests__/Admin/SystemSettings/Slideshow/Dialog.js
  src/__tests__/Admin/SystemSettings/Slideshow/Dropzone.js
  src/__tests__/Admin/SystemSettings/Slideshow/index.js
  src/apis/index.js
  src/components/Admin/SystemSettings/ConfigKeys/DeleteSystemSettingsDialog.js
  src/components/Admin/SystemSettings/ConfigKeys/UpdateSystemSettingsDialog.js
  src/components/Admin/SystemSettings/ConfigKeys/index.js
  src/components/Admin/SystemSettings/Slideshow/Dialog.js
  src/components/Admin/SystemSettings/Slideshow/Dropzone.js
  src/components/Admin/SystemSettings/Slideshow/constants.js
  src/components/Admin/SystemSettings/Slideshow/index.js
  src/components/Admin/SystemSettings/SystemSettings.js
  src/components/Dialog/DialogSection.react.js
  src/components/cms/SkillSlideshow/constants.js
  src/components/cms/SkillSlideshow/index.js
Labels: enhancement

#2517 Show Login on protected routes#2512
  src/components/NotFound/NotFound.react.js
  src/components/shared/ProtectedRoute.js
  src/redux/reducers/create.js
Labels: bug, enhancement

#2478 Enhance search functionality #2473
  src/apis/index.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/BrowseSkill/SearchBar.js
  src/redux/reducers/skills.js
Labels: enhancement

#2515 Fix Icon and name not portrayed as expected #2513
  src/components/NavigationBar/Styles.js
  src/components/NavigationBar/index.js
  src/redux/reducers/app.js
Labels: bug

#2537 Search Enhance #2532, #2531, #2536
  src/components/NavigationBar/SearchBar.js
  src/components/NavigationBar/Styles.js
  src/components/NavigationBar/index.js
  src/images/favicon.png
Labels: enhancement, feature

#2533 Fix Edit Skill in SkillCreator and bugs #2519
  src/components/cms/BotBuilder/BotBuilderPages/DesignViews/UIView.js
  src/components/cms/BotBuilder/BotWizard.js
  src/components/cms/Dashboard/Dashboard.js
  src/components/cms/SkillCreator/SkillWizard.js
  src/components/cms/SkillPage/SkillListing.js
  src/components/shared/CircleImage/index.js
  src/redux/reducers/create.js
Labels: bug, enhancement

#2543 Fix admin loading users #2524, antd to material-table#2198
  src/__tests__/Admin/ListSkills/ConfirmSkillDialog.js
  src/__tests__/Admin/ListUser/DeleteDialog.js
  src/__tests__/Admin/ListUser/DevicePanel/EditDeviceDialog.js
  src/__tests__/Admin/ListUser/DevicePanel/index.js
  src/__tests__/Admin/ListUser/EditUserRoleDialog.js
  src/__tests__/Admin/ListUser/ListUser.js
  src/__tests__/Admin/ListUser/index.js
  src/__tests__/components/shared/ConfirmDialog.js
  src/components/Admin/Admin.js
  src/components/Admin/ListSkills/ListSkills.js
  src/components/Admin/ListUser/DeleteDialog.js
  src/components/Admin/ListUser/DevicePanel/EditDeviceDialog.js
  src/components/Admin/ListUser/DevicePanel/index.js
  src/components/Admin/ListUser/EditUserRoleDialog.js
  src/components/Admin/ListUser/ListUser.js
  src/components/Admin/ListUser/constants.js
  src/components/Admin/ListUser/index.js
  src/components/Dialog/DialogSection.react.js
  src/components/shared/ConfirmDialog.js
Labels: enhancement

#2549 Fix TopMenu Popper#2545, Slider#2542, #2544
  src/components/Admin/SystemSettings/Slideshow/Dialog.js
  src/components/Admin/SystemSettings/Slideshow/Dropzone.js
  src/components/Admin/SystemSettings/Slideshow/constants.js
  src/components/Admin/SystemSettings/Slideshow/index.js
  src/components/NavigationBar/Popper.js
  src/components/NavigationBar/index.js
  src/components/cms/SkillSlideshow/index.js
Labels: bug

#2577 Remove antd package, migrate related components to material
  package.json
  public/index.html
  src/components/Admin/ListSkills/ListSkills.js
  src/components/Admin/ListUser/index.js
  src/components/Admin/SystemSettings/ConfigKeys/index.js
  src/components/Admin/SystemSettings/Slideshow/index.js
  src/components/cms/BotBuilder/BotBuilderPages/ConfigureViews/UIView.js
  src/components/cms/SkillCreator/SkillViews/CodeView.js
  src/components/shared/TableActionStyles.js
  src/index.css
Labels: Clean Up, refactor

#2500 Device Page: Add configuration options
  src/App.js
  src/__tests__/components/MyDevices/DevicesTable.js
  src/__tests__/components/MyDevices/MapContainer.js
  src/__tests__/components/MyDevices/RemoveDeviceDialog.js
  src/__tests__/components/MyDevices/index.js
  src/components/Dialog/DialogSection.react.js
  src/components/Settings/Settings.react.js
  src/components/cms/Dashboard/index.js
  src/components/cms/MyDevices/DeviceWizard.js
  src/components/cms/MyDevices/DevicesTable.js
  src/components/cms/MyDevices/MapContainer.js
  src/components/cms/MyDevices/RemoveDeviceDialog.js
  src/components/cms/MyDevices/index.js
Labels: enhancement, feature

#2538 Add speech box for skill example sentences on front, cat and all pages with skills
  src/__tests__/components/shared/SkillExampleBubble.js
  src/components/ChatApp/MessageComposer.react.js
  src/components/ChatApp/MessageSection/MessageSection.react.js
  src/components/Dialog/DialogSection.react.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/BrowseSkill/BrowseSkillByCategory.js
  src/components/cms/SkillCardGrid/SkillCardGrid.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/components/cms/SkillCardScrollList/SkillCard.js
  src/components/cms/SkillCardScrollList/SkillCardScrollList.js
  src/components/cms/SkillCardStyle.js
  src/components/cms/SkillPage/SkillListing.js
  src/components/shared/SkillExampleBubble.js
  src/redux/actionTypes/index.js
  src/redux/actions/skill.js
  src/redux/reducers/skill.js
Labels: enhancement, feature

#2594 Fixes #2496: Show banner and disable device settings in local env
  .env
  deploy.sh
  src/App.js
  src/components/cms/MyDevices/DeviceWizard.js
  src/components/cms/MyDevices/DevicesTable.js
  src/components/shared/AppBanner.js
  src/redux/reducers/app.js
Labels: feature

#2600 Fixes UI and i18n issue: 1-3 out of 3 result(s) #2579
  package.json
  src/components/cms/BrowseSkill/BrowseSkill.js
Labels: bug

#2593 Fix #2586
  src/components/shared/Lozenge.js
Labels: bug

#2599 Fix Search box color fix and dropdown view #2589
  src/components/NavigationBar/SearchBar.js
  src/components/NavigationBar/Styles.js
  src/components/NavigationBar/index.js
Labels: bug

#2631 Fixes #2630: Use common dialog for all use-cases
  src/__tests__/components/MyDevices/RemoveDeviceDialog.js
  src/__tests__/components/shared/ConfirmDialog.js
  src/components/Admin/ListSkills/ListSkills.js
  src/components/Auth/ChangePassword/ChangePassword.react.js
  src/components/Auth/ForgotPassword/ForgotPassword.react.js
  src/components/cms/MyDevices/RemoveDeviceDialog.js
  src/components/cms/SkillCreator/SkillWizard.js
  src/components/cms/SkillFeedbackCard/SkillFeedbackCard.js
  src/components/cms/SkillFeedbackPage/EditFeedbackDialog.js
  src/components/cms/SkillPage/SkillListing.js
  src/components/shared/Dialog/dialogTypes/ConfirmDialog.js
  src/components/shared/Dialog/index.js
Labels: refactor

#2624 Fix mobile view for skill search #2622
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/components/shared/SkillExampleBubble.js
Labels: bug

#2610 Fix remaining bugs and implement search bar in chat bubble
  src/components/ChatApp/MessageSection/MessageSection.react.js
  src/components/ChatApp/SearchField.react.js
Labels: enhancement

#2518 Add Configure Email settings in Admin#2454
  src/__tests__/Admin/Settings/ConfigKeys/UpdateSystemSettingsDialog.js
  src/__tests__/Admin/Settings/ConfigKeys/index.js
  src/__tests__/Admin/Settings/Mail/index.js
  src/__tests__/Admin/Settings/Slideshow/Dialog.js
  src/__tests__/Admin/Settings/Slideshow/Dropzone.js
  src/__tests__/Admin/Settings/Slideshow/index.js
  src/__tests__/Admin/Settings/index.js
  src/__tests__/components/shared/OutlinedTextField.js
  src/apis/index.js
  src/components/Admin/Admin.js
  src/components/Admin/Settings/ConfigKeys/UpdateSystemSettingsDialog.js
  src/components/Admin/Settings/ConfigKeys/index.js
  src/components/Admin/Settings/Mail/index.js
  src/components/Admin/Settings/Slideshow/Dialog.js
  src/components/Admin/Settings/Slideshow/Dropzone.js
  src/components/Admin/Settings/Slideshow/constants.js
  src/components/Admin/Settings/Slideshow/index.js
  src/components/Admin/Settings/index.js
  src/components/shared/Dialog/index.js
  src/components/shared/OutlinedTextField.js
  src/index.css
Labels: enhancement, feature

#2634 Add Google Analytics, Matoma/Piwik Tracking #2612
  package.json
  public/index.html
  src/App.js
  src/index.js
  src/withTracker.js
Labels: enhancement

#2658 Fix Components Remounting due to HOC #2657
  src/App.js
Labels: Priority: Urgent, bug

#2647 Fix list highlight on Customer Review Select #2646
  src/components/Settings/Settings.react.js
  src/components/cms/BrowseSkill/BrowseSkill.js
  src/components/cms/SkillCardList/SkillCardList.js
  src/redux/reducers/skills.js
  src/utils/appendQueryString.js
Labels: bug, enhancement

#2661 Fix validation #2546,#2555, searchbar bug #2640, avatar UI #2638
  src/__tests__/components/shared/Recaptcha.js
  src/apis/index.js
  src/components/Auth/ChangePassword/ChangePassword.react.js
  src/components/Auth/Login/Login.react.js
  src/components/Auth/SignUp/SignUp.react.js
  src/components/Settings/AccountTab.react.js
  src/components/Settings/Avatar.js
  src/components/shared/Recaptcha.js
  src/utils/isPassword.js
  src/utils/isUserName.js
Labels: UI/UX, bug, enhancement

#2664 Add server side validation for SignUp user, session storage for user
  src/apis/index.js
  src/components/Auth/Login/Login.react.js
  src/components/Auth/SignUp/SignUp.react.js
Labels: bug, enhancement

#2666 Show user, Statistics in Admin #2550, Skill Example #2635
  src/components/Admin/AdminTab/AdminTab.js
  src/components/cms/SkillPage/SkillListing.js
  src/components/cms/SkillRating/SkillRatingCard.js
  src/components/cms/SkillUsageCard/SkillUsageCard.js
  src/components/shared/charts/LineChart.js
  src/index.css
  src/utils/mergeByDate.js
  src/utils/sortByDate.js
Labels: bug, enhancement, refactor

#2674 Fix scroll behaviour on skill example, chatApp code
  src/App.js
  src/components/ChatApp/ChatApp.react.js
  src/components/ChatApp/MessageComposer.react.js
  src/components/ChatApp/MessageListItem/MessageListItem.react.js
  src/components/ChatApp/MessageSection/MessageSection.react.js
  src/components/ChatApp/SearchField.react.js
  src/components/NavigationBar/index.js
  src/components/cms/SkillSlideshow/index.js
  src/components/shared/Dialog/index.js
  src/components/shared/SkillExampleBubble.js
  src/redux/actionTypes/index.js
  src/redux/actions/messages.js
  src/redux/actions/skill.js
  src/redux/actions/ui.js
  src/redux/reducers/messages.js
  src/redux/reducers/skill.js
  src/redux/reducers/ui.js
  src/utils/generateMessage.js
  src/utils/index.js
  src/utils/testExample.js
Labels: Clean Up, bug, refactor

#2699 Enhance preview chat #1
  src/components/ChatApp/MessageSection/MessageSection.react.js
  src/components/ChatApp/SearchField.react.js
Labels: UI/UX

#2654 Admin: Bots
  src/__tests__/Admin/ListBots/index.js
  src/apis/index.js
  src/components/Admin/Admin.js
  src/components/Admin/ListBots/constants.js
  src/components/Admin/ListBots/index.js
  src/components/cms/BotBuilder/BotBuilder.js
  src/components/shared/Dialog/index.js
Labels: WIP, dependent on server

#2731 Fix signup into SUSI.AI issue
  src/components/Auth/SignUp/SignUp.react.js
Labels: Priority: High, bug

#2735 Fix Admin: Not able to delete account and top menu link ? to /about
  src/apis/index.js
  src/components/Admin/ListUser/index.js
  src/components/NavigationBar/index.js
Labels: Priority: High, bug

#2737 Fix Chat box: Full Screen Mode no longer working
  src/components/shared/Dialog/index.js
Labels: Priority: High, bug
